# Generated by Django 3.1.4 on 2021-03-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratProprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('surface_habitable', models.FloatField()),
                ('surface_balcon', models.FloatField()),
                ('capacite', models.IntegerField()),
                ('distance_pistes', models.FloatField()),
                ('status', models.CharField(choices=[('AVAIL', 'Disponible'), ('BUSY', 'Occuper'), ('OFF', 'Inactif')], default='AVAIL', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=200)),
                ('code_postale', models.IntegerField()),
                ('ville', models.CharField(max_length=200)),
                ('telephone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(auto_now_add=True)),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('status_reservation', models.CharField(choices=[('WAIT', 'En cours'), ('CANCEL', 'Annuler')], default='WAIT', max_length=6)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.profile')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.contratproprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='ProprietePrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('propriete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.contratproprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='ProprieteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('propriete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.contratproprietaire')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileProprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rib', models.CharField(max_length=50)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmation', models.DateField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='contratproprietaire',
            name='profileproprietaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.profileproprietaire'),
        ),
    ]
