# Generated by Django 3.1.4 on 2021-03-10 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='neige_soleil_app.reservation'),
        ),
    ]
