# Generated by Django 3.2 on 2021-04-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.reservation'),
        ),
    ]
