# Generated by Django 3.1.4 on 2021-02-14 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='PrixLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.location')),
            ],
        ),
    ]
