# Generated by Django 3.1.4 on 2021-03-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status_reservation',
            field=models.CharField(choices=[('WAIT', 'En cours'), ('LOCATION', 'Location'), ('CANCEL', 'Annuler')], default='WAIT', max_length=8),
        ),
    ]
