# Generated by Django 3.2 on 2021-04-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0002_alter_location_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
