# Generated by Django 3.1.4 on 2021-02-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0002_auto_20210214_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationsimages',
            old_name='locations',
            new_name='location',
        ),
    ]
