# Generated by Django 3.1.4 on 2021-02-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0003_auto_20210214_2129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationsImages',
            new_name='LocationImages',
        ),
    ]
