# Generated by Django 3.1.4 on 2021-02-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0004_auto_20210214_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationImages',
            new_name='LocationImage',
        ),
    ]
