# Generated by Django 3.1.4 on 2021-02-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0005_auto_20210214_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='description_breve',
            new_name='nom',
        ),
    ]
