# Generated by Django 3.1.4 on 2021-02-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0006_auto_20210216_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rib',
        ),
    ]
