# Generated by Django 3.1.4 on 2021-02-17 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neige_soleil_app', '0007_remove_profile_rib'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='ContratProprietaire',
        ),
        migrations.RenameModel(
            old_name='LocationImage',
            new_name='ProprieteImage',
        ),
        migrations.RenameModel(
            old_name='PrixLocation',
            new_name='ProprietePrix',
        ),
    ]
