# Generated by Django 3.1.4 on 2021-03-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neige_soleil_app', '0009_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proprieteimage',
            old_name='location',
            new_name='propriete',
        ),
        migrations.RenameField(
            model_name='proprieteprix',
            old_name='location',
            new_name='propriete',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='location',
            new_name='propriete',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status_reservation',
            field=models.CharField(choices=[('WAIT', 'En cours'), ('CANCEL', 'Annuler')], default='WAIT', max_length=6),
        ),
        migrations.CreateModel(
            name='ProfileProprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confirmation', models.DateField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='neige_soleil_app.reservation')),
            ],
        ),
    ]
